# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    npm test
    ng build --prod
  displayName: 'npm install and build'

- script: |
    npm install -g chromedriver
    CHROME_BIN=/usr/bin/google-chrome npm test -- --no-sandbox --headless --disable-gpu --disable-software-rasterizer
  displayName: 'Run tests with headless Chrome'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
